import express, { Request, Response } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import https from 'https';
import { ensureDatabaseExists, runMigrationsAndSeed, dbConfig } from './db';
import { apiResponseEncryptionMiddleware, AES_KEY_BUFFER } from './middleware/encryption';
import { startTelegramWeeklyScheduler } from './services/telegramService';
import { startRecycleBinPurgeScheduler } from './services/recycleBinService';

import authRoutes from './routes/authRoutes';
import healthRoutes from './routes/healthRoutes';
import activityRoutes from './routes/activityRoutes';
import projectRoutes from './routes/projectRoutes';
import taskRoutes from './routes/taskRoutes';
import memberRoutes from './routes/memberRoutes';
import recycleBinRoutes from './routes/recycleBinRoutes';
import telegramRoutes from './routes/telegramRoutes';
import notificationRoutes from './routes/notificationRoutes';
import attachmentRoutes from './routes/attachmentRoutes';
import shareRoutes from './routes/shareRoutes';

// Force system and runtime timezone to UTC+7 (Asia/Bangkok, Indochina Time)
process.env.TZ = 'Asia/Bangkok';
dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// ==========================================
// AES-256-GCM Response Encryption Middleware
// Encrypts all /api/* JSON responses (except /api/health)
// ==========================================
app.use('/api', apiResponseEncryptionMiddleware);

// ==========================================
// Serve Static Document Uploads
// ==========================================
const localUploadsDir = path.resolve(process.cwd(), 'uploads', 'documents');
if (!fs.existsSync(localUploadsDir)) {
  fs.mkdirSync(localUploadsDir, { recursive: true });
}
app.use('/api/uploads/documents', express.static(localUploadsDir));

// ==========================================
// Mount REST Route Modules
// ==========================================
app.use('/api/auth', authRoutes);
app.use('/api/health', healthRoutes);
app.use('/api/activities', activityRoutes);
app.use('/api/projects', projectRoutes);
app.use('/api/tasks', taskRoutes);
app.use('/api/members', memberRoutes);
app.use('/api/recycle-bin', recycleBinRoutes);
app.use('/api/telegram', telegramRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/attachments', attachmentRoutes);
app.use('/api/share', shareRoutes);

// ==========================================
// Serve Static Frontend (Single-Service Deployment)
// ==========================================
const distPath = path.resolve(process.cwd(), 'dist');
if (fs.existsSync(distPath)) {
  console.log(`[Server] Serving static frontend from: ${distPath}`);
  app.use(express.static(distPath));
  app.get('*', (req: Request, res: Response) => {
    if (!req.path.startsWith('/api')) {
      res.sendFile(path.join(distPath, 'index.html'));
    }
  });
}

// ==========================================
// Start Server & Bootstrap Database
// ==========================================
async function startServer() {
  try {
    console.log('[Server] Checking PostgreSQL database initialization...');
    await ensureDatabaseExists();
    await runMigrationsAndSeed();
    console.log('[Server] Database initialization completed successfully.');

    // Start background schedulers
    startTelegramWeeklyScheduler();
    startRecycleBinPurgeScheduler();
  } catch (err: any) {
    console.error('[Server] Warning: Failed to auto-initialize database on startup:', err.message);
    console.error('[Server] If PostgreSQL credentials are needed, please verify your .env file.');
  }

  // Use HTTPS if certs exist (generated by mkcert), otherwise fall back to HTTP
  const certPath = path.resolve(process.cwd(), 'certs/localhost+1.pem');
  const keyPath = path.resolve(process.cwd(), 'certs/localhost+1-key.pem');
  const certsExist = fs.existsSync(certPath) && fs.existsSync(keyPath);

  if (certsExist) {
    const sslOptions = {
      cert: fs.readFileSync(certPath),
      key: fs.readFileSync(keyPath),
    };
    https.createServer(sslOptions, app).listen(PORT, () => {
      console.log(`=======================================================`);
      console.log(`🔐 API Server running at: https://localhost:${PORT}`);
      console.log(`🔒 HTTPS enabled with mkcert certificate`);
      console.log(`🛡️  AES-256-GCM payload encryption: ${AES_KEY_BUFFER ? 'ENABLED' : 'DISABLED (no key)'}`);
      console.log(`🐘 PostgreSQL Host: ${dbConfig.host}:${dbConfig.port}`);
      console.log(`🗄️ Database: ${dbConfig.database}`);
      console.log(`=======================================================`);
    });
  } else {
    // Fallback to HTTP if certs are missing
    app.listen(PORT, () => {
      console.log(`=======================================================`);
      console.log(`🚀 API Server running at: http://localhost:${PORT}`);
      console.log(`⚠️  HTTPS disabled — run mkcert to enable SSL`);
      console.log(`🛡️  AES-256-GCM payload encryption: ${AES_KEY_BUFFER ? 'ENABLED' : 'DISABLED'}`);
      console.log(`🐘 PostgreSQL Host: ${dbConfig.host}:${dbConfig.port}`);
      console.log(`🗄️ Database: ${dbConfig.database}`);
      console.log(`=======================================================`);
    });
  }
}

startServer();
